/*
This has been generated by the overpass-turbo wizard.
The original search was:
“place = city”
*/
[out:json][timeout:600];
// gather results
(
  // query part for: “place=city”
  node["place"="city"]({{bbox}});
  //way["place"="city"]({{bbox}});
 // relation["place"="city"]({{bbox}});
);
// print results
out body;
>;
out skel qt;