/*
This has been generated by the overpass-turbo wizard.
The original search was:
"place=neighbourhood"

[out:csv(::id,::lon,::lat,"place","name","name:en","name:zh","wikipedia","wikidata")];
*/
[out:json];
// gather results
(
  // query part for: "place=neighbourhood"
  node["place"="neighbourhood"](%s);
 
  
  node["place"="suburb"](%s);
 
 
);
// print results
out body;
>;
out skel qt;